# Generated by Django 4.1.1 on 2023-01-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_respuesta_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='requerimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
