# Generated by Django 4.1.1 on 2023-01-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_respuesta_comentario_respuesta_requerimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
