# Generated by Django 4.1.1 on 2023-02-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_categoria_alter_respuesta_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
    ]
