# Generated by Django 4.1.1 on 2023-02-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_datecompleted_remove_task_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='title',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='code',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
