# Generated by Django 4.1.1 on 2023-02-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_respuesta_title_respuesta_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='requerimiento',
        ),
        migrations.AddField(
            model_name='task',
            name='respuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.respuesta'),
            preserve_default=False,
        ),
    ]
