# Generated by Django 4.1.1 on 2023-02-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_respuesta_respuesta_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='code',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
