# Generated by Django 4.1.1 on 2023-02-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_solicitud_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='code',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
