# Generated by Django 4.1.1 on 2023-02-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_solicitud_code_alter_solicitud_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='title',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En espera'), (2, 'En proceso'), (3, 'Terminado')]),
        ),
    ]
