# Generated by Django 4.1.1 on 2023-02-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_solicitud_title_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
