# Generated by Django 4.1.1 on 2023-02-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_solicitud_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='title',
        ),
    ]
