# Generated by Django 4.1.1 on 2023-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_task_respuesta_respuesta_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='formulario',
            field=models.URLField(blank=True, null=True),
        ),
    ]
