# Generated by Django 4.1.1 on 2023-02-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
