# Generated by Django 4.1.1 on 2023-02-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_user_is_ejecutivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='adress',
        ),
    ]
