# Generated by Django 4.1.1 on 2023-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='description',
            new_name='comentario',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'En espera del cliente'), (4, 'Resuelto')], default=1),
        ),
    ]
